org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=256m
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Disable incremental Kotlin compilation to avoid cross-drive relative path issues
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
